spring.application.name=sagamovies

spring.datasource.url=jdbc:mysql://localhost:3306/sagamovies
spring.datasource.username=root
spring.datasource.password=Somu@9114

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# defining max size

spring.servlet.multipart.max-file-size=10GB
spring.servlet.multipart.max-request-size=10GB

server.tomcat.max-http-form-post-size=-1
server.tomcat.connection-timeout=600000

springdoc.api-docs.path=/api-docs

springdoc.swagger-ui.path=/swagger-ui.html



# Tomcat-specific multipart settings
server.tomcat.max-swallow-size=-1
